### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by mikecopestake**
Hi @schillermann!

Thank you so much for your amazing work on this project and for sharing it publicly.

I have been working on adding some simple translation to allow me to maintain an English version and would be very grateful if you could pull this into your version so that I can update more easily in the future without having to manually translate pages.

I'm quite new to GitHub, so please tell me if I've done anything wrong here or can improve my repository or the pull request.

Many thanks,
Mike

### CODE REVIEW

**Comment by schillermann** [comment]
@mikecopestake what do you think of i18n, mentioned in this [issue](https://github.com/schillermann/trolleydienst-php/issues/1), for the translation?
What are the pros and cons in your opinion?

**Comment by mikecopestake** [comment]
@schillermann thank you for merging. I'm not a very good coder, but I'd be happy to join and help with what I can.

As for i18n, I have no experience with it, the pros seem to be that it has cache, the cons are that it requires an external script to work.

The method I implemented is just using a simple function that replaces strings, so it doesn't require anything external, but it is all manual which may present a problem.

What this means is, that if any strings aren't translated they will show in German, but for each new translation the whole translation file can be copied and the strings changed.

My reason for doing it this way was to keep it simple as a starting point, if you have an idea for a better way or would like to change it, that is no problem.

**Comment by schillermann** [comment]
Hello @mikecopestake,

I see it the same way as you with i18n.
You have already helped the project a lot with the English translation.
Good job.
If you find anything else that can be translated, feel free to change it.
I added you to the project.

Greetings
Mario

**Comment by mikecopestake** [comment]
Thank you @schillermann, you've done a great job with the project, it is very much appreciated!

**Pull request merged**
