### PR TITLE
SMTP Email & Tweaks

### PR DESCRIPTION
**Pull request by mikecopestake**
This contains the following changes:

- Apply/Withdraw popup added when on shift page to prevent accidental applications
- Shift length input changed to text so as to allow decimals (e.g. 1.5hrs)
- Added 'Resend Welcome Email' button to profile edit page to remind users of their login details
- Altered send_mail_plain.php to add SMTP and SendinBlue as options for transactional mail delivery
- Corrected a few typos in English

### CODE REVIEW

**Comment by schillermann** [comment]
Hi @mikecopestake,

thank you for your effort.

Greetings
Mario

**Comment by schillermann** [comment]
@mikecopestake feel free to bring changes directly into the master.
It is sufficient if you create an issue for what you are planning.
Then everyone will know about it

**Comment by mikecopestake** [comment]
@schillermann thank you.

I'm not very good with GitHub, and changes like this are quite big, and probably not coded very well, so I appreciate you checking it out first yo hopefully catch any big mistakes!

Is it best in the future to create an issue for something I plan to add, then do it, make the changes directly to master and mark the issue as complete?

**Comment by schillermann** [comment]
Hi @mikecopestake,

you can create here a new branch like `feature/xyz` from master branch.
If you are not sure, you can also create a pull request from your branch.
But it doesn't have to be.
If something is wrong, it can always be corrected later in the master branch.
A new version is not created for each commit in the master.
First of all, it is important that the master version is always executable.

You described the process correctly.
You can also specify the id of the issue with the hash symbol as prefix in the comment, when merging into the master.
This creates a link to the issue.

Greetings
Mario

**Comment by schillermann** [comment]
@mikecopestake if you want me to look at your changes, you can write to me in the issue before or after the merge and then assign it to me.
Then I know that I should look at the changes.

**Pull request merged**
